version: "3.9"

services:
  # --------------------------------------------------------
  # TimescaleDB (unchanged)
  # --------------------------------------------------------
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    restart: unless-stopped

  # --------------------------------------------------------
  # Separate Redis instances for each Raft node
  # --------------------------------------------------------
  redis1:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    restart: unless-stopped

  redis2:
    image: redis:7-alpine
    ports:
      - "6382:6379"
    restart: unless-stopped

  redis3:
    image: redis:7-alpine
    ports:
      - "6383:6379"
    restart: unless-stopped

  redis4:
    image: redis:7-alpine
    ports:
      - "6384:6379"
    restart: unless-stopped

  redis5:
    image: redis:7-alpine
    ports:
      - "6385:6379"
    restart: unless-stopped

  # --------------------------------------------------------
  # 5 RAFT NODES (INGESTION + RAFT)
  # --------------------------------------------------------

  ingestion1:
    build:
      context: .
      dockerfile: services/ingestion/Dockerfile
    container_name: node1
    environment:
      - NODE_ID=node1
      - NODE_PORT=50051
      - PEERS=node2:50052,node3:50053,node4:50054,node5:50055
      - REDIS_ADDR=redis1:6379
    depends_on:
      - redis1
    ports:
      - "50051:50051"
    restart: unless-stopped

  ingestion2:
    build:
      context: .
      dockerfile: services/ingestion/Dockerfile
    container_name: node2
    environment:
      - NODE_ID=node2
      - NODE_PORT=50052
      - PEERS=node1:50051,node3:50053,node4:50054,node5:50055
      - REDIS_ADDR=redis2:6379
    depends_on:
      - redis2
    ports:
      - "50052:50052"
    restart: unless-stopped

  ingestion3:
    build:
      context: .
      dockerfile: services/ingestion/Dockerfile
    container_name: node3
    environment:
      - NODE_ID=node3
      - NODE_PORT=50053
      - PEERS=node1:50051,node2:50052,node4:50054,node5:50055
      - REDIS_ADDR=redis3:6379
    depends_on:
      - redis3
    ports:
      - "50053:50053"
    restart: unless-stopped

  ingestion4:
    build:
      context: .
      dockerfile: services/ingestion/Dockerfile
    container_name: node4
    environment:
      - NODE_ID=node4
      - NODE_PORT=50054
      - PEERS=node1:50051,node2:50052,node3:50053,node5:50055
      - REDIS_ADDR=redis4:6379
    depends_on:
      - redis4
    ports:
      - "50054:50054"
    restart: unless-stopped

  ingestion5:
    build:
      context: .
      dockerfile: services/ingestion/Dockerfile
    container_name: node5
    environment:
      - NODE_ID=node5
      - NODE_PORT=50055
      - PEERS=node1:50051,node2:50052,node3:50053,node4:50054
      - REDIS_ADDR=redis5:6379
    depends_on:
      - redis5
    ports:
      - "50055:50055"
    restart: unless-stopped

  # --------------------------------------------------------
  # Aggregator (unchanged)
  # --------------------------------------------------------
  aggregator:
    build:
      context: .
    dockerfile: services/aggregator/Dockerfile
    environment:
      - REDIS_ADDR=redis1:6379   # reads from node1's replicated stream
    depends_on:
      - redis1
    ports:
      - "50060:50053"
    restart: unless-stopped

  # --------------------------------------------------------
  # Alerter (unchanged)
  # --------------------------------------------------------
  alerter:
    build:
      context: .
      dockerfile: services/alerter/Dockerfile
    environment:
      - REDIS_ADDR=redis1:6379
    depends_on:
      - redis1
    ports:
      - "50061:50054"
    restart: unless-stopped

  # --------------------------------------------------------
  # Query API (TimescaleDB reader)
  # --------------------------------------------------------
  queryapi:
    build:
      context: .
      dockerfile: services/query-api/Dockerfile
    depends_on:
      - timescaledb
    ports:
      - "50062:50052"
    restart: unless-stopped

  # --------------------------------------------------------
  # Grafana Dashboard
  # --------------------------------------------------------
  grafana:
    image: grafana/grafana:11.1.0
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - timescaledb
    ports:
      - "3300:3000"
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  redis1-data:
  redis2-data:
  redis3-data:
  redis4-data:
  redis5-data:
  pg-data:
  grafana-data:
